// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension CarambolicSchema {
  /// Autogenerated input type of StoryCreate
  struct StoryCreateInput: InputObject {
    private(set) var __data: InputDict

    init(_ data: InputDict) {
      __data = data
    }

    init(
      clientMutationId: GraphQLNullable<String> = nil,
      storyInput: StoryInput
    ) {
      __data = InputDict([
        "clientMutationId": clientMutationId,
        "storyInput": storyInput
      ])
    }

    /// A unique identifier for the client performing the mutation.
    var clientMutationId: GraphQLNullable<String> {
      get { __data["clientMutationId"] }
      set { __data["clientMutationId"] = newValue }
    }

    var storyInput: StoryInput {
      get { __data["storyInput"] }
      set { __data["storyInput"] = newValue }
    }
  }

}