// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension CarambolicSchema.Objects {
  /// Autogenerated return type of StoryCreate.
  static let StoryCreatePayload = ApolloAPI.Object(
    typename: "StoryCreatePayload",
    implementedInterfaces: []
  )
}